version: '3.5'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      BASE_URL: ${BASE_URL:-"https://localhost"}
      MAP_LOGIN_ID:
      MAP_LOGIN_PWD:
    #volumes:
      #- "./src:/usr/share/nginx/html/"

  test:
    build:
      context: .
      target: build-deps
    environment:
      - NODE_ENV=test
    command: /deploy/test.sh
