version: '3.5'
services:
  web:
    build: .
    ports:
      - "8080:80"

  test:
    build:
      context: .
      target: build-deps
    environment:
      - NODE_ENV=test
    command: /deploy/test.sh
